name: kavita

services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${PATH_CONFIG}:/config
      - ${PATH_DATA}:/data
    ports:
      - 5000:5000
    restart: unless-stopped
