name: myspeed

services:
  myspeed:
    image: germannewsmaker/myspeed
    container_name: myspeed
    ports:
      - "5216:5216"
    volumes:
      - myspeed:/myspeed/data
    restart: unless-stopped

volumes:
  myspeed:
