services:
  myspeed:
    image: germannewsmaker/myspeed
    container_name: myspeed
    restart: unless-stopped
    ports:
      - "5216:5216"
    volumes:
      - app_data:/myspeed/data

volumes:
  app_data:
