services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - PGID=${GUID:-1000}
      - TZ=${TZ:-America/New_York}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM} # optional
    volumes:
      - ${CONFIG_PATH}:/config
      - ${MOVIES_PATH}:/movies
      - ${TV_PATH}:/tv
      - ${MUSIC_PATH}:/music
      - ${PHOTOS_PATH}:/photos
    devices:
      - /dev/dri:/dev/dri # for hardware acceleration
