name: phpipam

services:
  phpipam-web:
    image: phpipam/phpipam-www:latest
    ports:
      - "80:80"
    environment:
      - TZ=${TZ:-America/New_York}
      - IPAM_DATABASE_HOST=${IPAM_DATABASE_HOST}
      - IPAM_DATABASE_PASS=${IPAM_DATABASE_PASS}
      - IPAM_DATABASE_WEBHOST=%
    restart: unless-stopped
    volumes:
      - phpipam-logo:/phpipam/css/images/logo
      - phpipam-ca:/usr/local/share/ca-certificates:ro
    depends_on:
      - phpipam-mariadb

  phpipam-cron:
    image: phpipam/phpipam-cron:latest
    environment:
      - TZ=${TZ:-America/New_York}
      - IPAM_DATABASE_HOST=${IPAM_DATABASE_HOST:-phpipam-mariadb}
      - IPAM_DATABASE_PASS=${IPAM_DATABASE_PASS}
      - SCAN_INTERVAL=${SCAN_INTERVAL:-1h}
    restart: unless-stopped
    volumes:
      - phpipam-ca:/usr/local/share/ca-certificates:ro
    depends_on:
      - phpipam-mariadb

  phpipam-mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${IPAM_DATABASE_PASS}
    restart: unless-stopped
    volumes:
      - phpipam-db-data:/var/lib/mysql

volumes:
  phpipam-db-data:
  phpipam-logo:
  phpipam-ca:
