name: bookstack

services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - APP_URL=${APP_URL}
      - APP_KEY=${APP_KEY}
      - DB_HOST=bookstack-db
      - DB_PORT=3306
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION} # optional
    volumes:
      - ${PATH_CONFIG}:/config
    ports:
      - 6875:80
    restart: unless-stopped

  bookstack-db:
    image: mysql:${MYSQL_VERSION}
    container_name: bookstack-db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${PATH_DB}:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped
