name: gitea-postgres

services:
  server:
    image: gitea/gitea:${GITEA_VERSION:-latest}
    container_name: gitea
    environment:
      - USER_UID=${UID:-1000}
      - USER_GID=${GID:-1000}
      - GITEA__database__DB_TYPE=${DB_TYPE:-postgres}
      - GITEA__database__HOST=db:${DB_HOST:-5432}
      - GITEA__database__NAME=${DB_NAME:-gitea}
      - GITEA__database__USER=${DB_USER:-gitea}
      - GITEA__database__PASSWD=${DB_PASSWD}
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: postgres:${POSTGRES_VERSION:-16}
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER:-gitea}
      - POSTGRES_PASSWORD=${DB_PASSWD}
      - POSTGRES_DB=${DB_NAME:-gitea}
    networks:
      - gitea
    volumes:
      - ${PATH_DB}:/var/lib/postgresql/data

networks:
  gitea:
    external: false
