services:
  rustdesk-hbbs:
    container_name: rustdesk-hbbs
    image: rustdesk/rustdesk-server:latest
    restart: unless-stopped
    command: hbbs
    network_mode: "host"
    #environment:
    depends_on:
      - rustdesk-hbbr
    volumes:
      - hbbs_data:/root

  rustdesk-hbbr:
    container_name: rustdesk-hbbr
    image: rustdesk/rustdesk-server:latest
    restart: unless-stopped
    command: hbbr
    network_mode: "host"
    volumes:
      - hbbr_data:/root

volumes:
  hbbs_data:
  hbbr_data:
